### ISSUE TITLE
column formatting issue

### ISSUE THREAD

**Issue by pengisgood** [biztech-it/BTable#11]
When I have some numeric numbers in the column, I don't want the default rounding convention.
Is there a way the set column width and data format?

**Comment by lucapazz** [comment]
BTable uses the format defined in the "formatString" attribute of your Mondrian schema.
Have you set a format string for those measures?
Did you put decimals in your format strings?

**Comment by pengisgood** [comment]
Thanks for your reply!
I do have a formatString in the schema, which is "#.##%".

**Comment by lucapazz** [comment]
You can see the meaning of characters **#** and **0** [here] (https://msdn.microsoft.com/en-us/library/ms146084.aspx). Remind that when you use % in a format string the value is multiplied by 100.
