### ISSUE TITLE
update filter button not reachable

### ISSUE THREAD

**Issue by jaapandre** [biztech-it/BTable#13]
When I want to update a filter in btable 2.1 on pentaho 5.4 (firefox/chrome) I can't reach the update filter button. According to the tutorial video at https://youtu.be/IYAlYdtZHwk?t=114 I should close the Filter section and the update filter appears. But nothing happens when I click the x at the filter bar.

**Comment by bonomma** [comment]
I'm going to release a new version today or tomorrow with bug fixing, new features and support for Pentaho 7.0. Be patient!! :D

**Comment by jaapandre** [comment]
Don't keep me waiting... ;-) I hope it is not affected by http://jira.pentaho.com/browse/MARKET-350 (installing from sourceforge does not seem to work for me :-()

**Comment by bonomma** [comment]
New versions available in Sourceforce. Version 3.0 is the one for Pentaho 5.x. Follow this installation instructions if you want to view samples with templates http://bonomma.blogspot.it/2017/01/btable-pre-or-post-installation.html
