### ISSUE TITLE
Error generating MDX query with multiselect parameters

### ISSUE THREAD

**Issue by mdpkishore** [biztech-it/BTable#17]
Hi,

I am creating a Btable dashboard(pentaho 6) with mutiple hierarchy filters with ability to choose multiple options at each level. However it throws the below Exception when i try to apply more than 2 filters. I verified the data that is being passed to the btable component but it looks fine. Looks like the Btable component is not generating the query properly

Caused by: mondrian.olap.MondrianException: Mondrian Error:No function matches signature '<Set> AND <Logical Expression>'
        at mondrian.resource.MondrianResource$_Def0.ex(MondrianResource.java:984)
        at mondrian.olap.ValidatorImpl.getDef(ValidatorImpl.java:209)
        at mondrian.olap.fun.FunUtil.resolveFunArgs(FunUtil.java:2057)
        at mondrian.mdx.UnresolvedFunCall.accept(UnresolvedFunCall.java:102)
        at mondrian.olap.ValidatorImpl.validate(ValidatorImpl.java:83)
        at mondrian.olap.Formula.accept(Formula.java:107)
        at mondrian.olap.ValidatorImpl.validate(ValidatorImpl.java:159)
        at mondrian.olap.Query.resolve(Query.java:581)
        at mondrian.olap.Query.resolve(Query.java:476)
        at mondrian.olap.Query.<init>(Query.java:200)
        at mondrian.olap.Query.<init>(Query.java:161)
        at mondrian.olap.Parser$FactoryImpl.makeQuery(Parser.java:927)
        at mondrian.parser.MdxParserImpl.selectStatement(MdxParserImpl.java:1241)

Regards
Kishore

**Comment by jaapandre** [comment]
If I use the steelwheels model via btable analyzer and filter 3 levels. I also get an empty table:
eg: Territory -> APAC,	Country -> Australia,	State Province	-> NSW

Feb 20, 2017 10:42:24 AM com.sun.jersey.spi.container.ContainerResponse logException
SEVERE: Mapped exception to response: 501
javax.ws.rs.WebApplicationException: pt.webdetails.cda.dataaccess.QueryException: Mondrian Error:Failed to parse query 'with set [Markets_Territory_Set] as 'Filter({[Markets].[Territory].Members}, ([Markets].[Territory].CurrentMember.Name = "APAC"))' set [Markets_Country_Set] as 'Filter(Filter({[Markets].[Country].Members}, ([Markets].[Country].CurrentMember.Name = "Australia")), ((Exists(Ancestor([Markets].CurrentMember, [Markets].[Territory]), [Markets_Territory_Set]).Count > 0))))' set [Markets_State Province_Set] as 'Filter(Filter({[Markets].[State Province].Members}, ([Markets].[State Province].CurrentMember.Name = "NSW")), ((Exists(Ancestor([Markets].CurrentMember, [Markets].[Territory]), [Markets_Territory_Set]).Count > 0)) AND (Exists(Ancestor([Markets].CurrentMember, [Markets].[Country]), [Markets_Country_Set]).Count > 0))))' set [Markets_City_Set] as 'Filter({[Markets].[City].Members}, ((Exists(Ancestor([Markets].CurrentMember, [Markets].[Territory]), [Markets_Territory_Set]).Count > 0)) AND (Exists(Ancestor([Markets].CurrentMember, [Markets].[Country]), [Markets_Country_Set]).Count > 0)) AND (Exists(Ancestor([Markets].CurrentMember, [Markets].[State Province]), [Markets_State Province_Set]).Count > 0))))'  Member [Measures].[Measure0] As '([Measures].[Fact Count])' set [Measures_Set] as '{[Measures].[Measure0]}'  select NON EMPTY [Measures_Set] on COLUMNS ,  NON EMPTY Descendants([Markets_City_Set], [Markets].[City], SELF) on ROWS from [SteelWheelsSales]'
	at pt.webdetails.cda.CdaUtils.doQuery(CdaUtils.java:183)

**Comment by lucapazz** [comment]
I think I have found the small bug: BTable is not putting brackets around the logical expressions.
@jaapandre's query should be (in bold the missing brackets):

with 
set [Markets_Territory_Set] as 'Filter({[Markets].[Territory].Members}, ([Markets].[Territory].CurrentMember.Name = "APAC"))' 
set [Markets_Country_Set] as 'Filter(Filter({[Markets].[Country].Members}, ([Markets].[Country].CurrentMember.Name = "Australia")), ((Exists(Ancestor([Markets].CurrentMember, [Markets].[Territory]), [Markets_Territory_Set]).Count > 0))))' 
set [Markets_State Province_Set] as 'Filter(Filter({[Markets].[State Province].Members}, ([Markets].[State Province].CurrentMember.Name = "NSW")), **(** ((Exists(Ancestor([Markets].CurrentMember, [Markets].[Territory]), [Markets_Territory_Set]).Count > 0)) AND (Exists(Ancestor([Markets].CurrentMember, [Markets].[Country]), [Markets_Country_Set]).Count > 0)))) **)**' 
set [Markets_City_Set] as 'Filter({[Markets].[City].Members}, **(** ((Exists(Ancestor([Markets].CurrentMember, [Markets].[Territory]), [Markets_Territory_Set]).Count > 0)) AND (Exists(Ancestor([Markets].CurrentMember, [Markets].[Country]), [Markets_Country_Set]).Count > 0)) AND (Exists(Ancestor([Markets].CurrentMember, [Markets].[State Province]), [Markets_State Province_Set]).Count > 0)))) **)**' Member [Measures].[Measure0] As '([Measures].[Fact Count])' 
set [Measures_Set] as '{[Measures].[Measure0]}' 
select NON EMPTY [Measures_Set] on COLUMNS , 
NON EMPTY Descendants([Markets_City_Set], [Markets].[City], SELF) on ROWS 
from [SteelWheelsSales]

**Comment by bonomma** [comment]
Solved with commit on 21/02/2017. Thanks Kishore and Japp-Andre for error reports and Luca for solution.
