### ISSUE TITLE
Coloring the cells

### ISSUE THREAD

**Issue by bhericher** [biztech-it/BTable#7]
Tools like JPivot or Saiku can handle the coloring of celles as specified in the schema of the cube, e.g. : 

<CalculatedMemberProperty name="format_string" expression="Iif(([Measures].[%foo]&#60;20.00),&#39;|#,##0.00|style=green&#39;,Iif(([Measures].[%foo]&#60;50.00),&#39;|#,##0.00|style=yellow&#39;,&#39;|#,##0.00|style=red&#39;))">

It would be nice that Btable supports it.

Benoit

**Comment by bonomma** [comment]
With new BTable versions 3.0 and 3.6 you can use "templates" for styling BTable and set CSS based alarms like these:
![immagine](https://cloud.githubusercontent.com/assets/2012959/21961107/3afdbc78-db01-11e6-94bf-0e2d826ed276.png)
