### ISSUE TITLE
Drill in cell

### ISSUE THREAD

**Issue by bhericher** [biztech-it/BTable#9]
The drill could be activated with a "left click" in a cell. 
As for displaying the facts corresponding to a measure, one should be able to provide a customized query.

Benoit

**Comment by bonomma** [comment]
With "facts corresponding to a measure" you mean dimensions? That is, you would like to select with dimensions are available for each measure?

**Comment by bhericher** [comment]
My request was not very clear, sorry! I assume that you know JPivot : when you drill in a cell, JPivot displays a second table at the bottom of the screen with the detail of the facts that prduce the measure in the selected cell. But you have no control of the query it generates for that. With Btable, its the same thing when you select 'drill in cell' from the contextual menu.
I would like to control this query for the following use case : a user sees that the amount of sales in Europe is growing of x% during the last month. If he drills in the cell, he will see all the sales in Europe during last month, even if he is concerned ( and has only rights to see) by those of France (or Italy if you prefer :+1: ). 
Hope my request is clearer

Thank you

**Comment by bhericher** [comment]
I eventually found a solution, but it would be fine to have something well packaged

Benoit
